[platformio]
default_envs = robot

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra

[env:robot]
build_src_filter = +<*> -<calibrate.cpp>

[env:calibrate]
build_src_filter = +<calibrate.cpp>